# Generated by Django 2.1.3 on 2018-11-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('bajada', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link_noticia', models.CharField(max_length=200)),
                ('link_recurso', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('contador_visitas', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_universidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'universidad',
                'verbose_name_plural': 'universidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_universidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.Universidad'),
        ),
    ]
