# Generated by Django 2.1.3 on 2018-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contador_visitas',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
