# Generated by Django 2.1.3 on 2018-12-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181210_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contador_visitas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
