# Generated by Django 2.1.3 on 2019-06-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190531_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_region', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'región',
                'verbose_name_plural': 'regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='universidad',
            name='region',
            field=models.CharField(max_length=2),
        ),
    ]
