# Generated by Django 2.1.3 on 2019-06-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190610_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
