# Generated by Django 2.1.3 on 2019-06-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190610_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id_universidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='news.Universidad'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='news.Region', to_field='numero_region'),
        ),
    ]
