# Generated by Django 2.2.11 on 2020-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190610_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='bajada_busqueda',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo_busqueda',
            field=models.CharField(default='', max_length=200),
        ),
    ]
